      - name: Download TMDB Dataset
        run: |
          mkdir -p data
          kaggle datasets download -d rounakbanik/the-movies-dataset -p data --force
          cd data
          unzip -o the-movies-dataset.zip
          rm the-movies-dataset.zip

          # REMOVE LARGE FILES (over 100MB)
          rm -f credits.csv
          rm -f ratings.csv
